FROM ubuntu

MAINTAINER bhuludondeti@gmail.com

RUN apt-get -y update && apt-get -y upgrade \
    && apt-get -y install openjdk-8-jdk wget gnupg2

RUN mkdir /var/lib/jenkins
WORKDIR /opt
 RUN apt-get install sudo

RUN wget -q -O - https://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo apt-key add -
RUN sudo sh -c  'echo  deb https://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/kenkins.list'


RUN  sudo apt-get update && apt-get install jenkins -y
EXPOSE 8080
ENTRYPOINT ["jenkins"]


